name: Daily Update Workflow
on:
  schedule:
    - cron: '5 5 * * *'

jobs:
  modify_labels:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      
      - name: Modify labels.json using Python script
        run: |
          python scrape.py

      - name: Commit and push changes
        run: |
          git config --global user.name "frishberg"
          git config --global user.email "frishberg@uchicago.edu"
          
          git add labels.json
          git add labels.js
          git commit -m "daily update of labels.json"
          git push
